version: '3'

services:
  app:
    image: katleta/test-web-app:latest
    ports:
      - 9000:9000
    env_file:
      - .env

  db:
    image: postgres
    env_file: 
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
    postgres:
        driver: bridge

volumes:
  postgres:
