version: "3.8"

services:
  app:
    image: katleta/test-web-app:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env.production.local
    networks:
      - postgres
    depends_on:
      - db
      - sqitch

  db:
    image: postgres
    env_file: 
      - .env.production.local
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres

  sqitch:
    image: sqitch/sqitch:v1.5.0.0
    command: deploy --verify --target db:pg://db/
    volumes:
      - ./sqitch.conf:/repo/sqitch.conf
      - ./migrations/:/repo/migrations
    restart: on-failure:1
    networks:
      - postgres
    depends_on:
      - db
    env_file:
      - .env.production.local
    environment:
      SQITCH_PASSWORD: ${POSTGRES_PASSWORD}
      SQITCH_USERNAME: ${POSTGRES_USER}

networks:
  postgres:
    driver: overlay

volumes:
  postgres:
