version: '3'

services:
  app:
    image: katleta/test-web-app:latest
    volumes:
      - sqlite_data:/home/app/databases/
    ports:
      - 80:9000
    env_file:
      - .env

volumes:
  sqlite_data:
