services:
  app:
    platform: linux/amd64
    image: webapp
    build:
      context: .
    volumes:
      - sqlite_data:/home/app/databases/
    ports:
      - 80:9000
    env_file:
      - .env

volumes:
  sqlite_data:
