name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  sqitch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: sqitch
        uses: ./.github/actions/sqitch

      - name: Create env file
        run: |
          touch .env
          echo 'GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}' >> .env
          echo 'GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}' >> .env
          echo 'GOOGLE_REDIRECT_URI=${{ vars.GOOGLE_REDIRECT_URI }}' >> .env
          echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_USER }}' >> .env
          echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> .env
          echo 'DB_CONNECTION=${{ vars.DB_CONNECTION }}' >> .env
          echo 'TELEGRAM_BOT_TOKEN=${{ secrets.DEMO_TELEGRAM_BOT_TOKEN }}' >> .env
          echo 'TELEGRAM_BOT_NAME=${{ secrets.DEMO_TELEGRAM_BOT_NAME }}' >> .env
          echo 'JWT_SECRET=${{ secrets.DEMO_JWT_SECRET }}' >> .env
          cat .env

      - name: Run migration
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          args: compose run sqitch
  # push_to_registry:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #
  #     - name: Build and push Docker image
  #       id: push
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: katleta/test-web-app:latest
  #
  # deploy:
  #   needs: push_to_registry
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout codebase
  #       uses: actions/checkout@v2
  #
  #     - name: Create env file
  #       run: |
  #         touch .env
  #         echo 'GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}' >> .env
  #         echo 'GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}' >> .env
  #         echo 'GOOGLE_REDIRECT_URI=${{ vars.GOOGLE_REDIRECT_URI }}' >> .env
  #         echo 'DB_CONNECTION=${{ vars.DB_CONNECTION }}' >> .env
  #         echo 'TELEGRAM_BOT_TOKEN=${{ secrets.DEMO_TELEGRAM_BOT_TOKEN }}' >> .env
  #         echo 'TELEGRAM_BOT_NAME=${{ secrets.DEMO_TELEGRAM_BOT_NAME }}' >> .env
  #         echo 'JWT_SECRET=${{ secrets.DEMO_JWT_SECRET }}' >> .env
  #         cat .env
  #
  #     - name: Deploy
  #       uses: kitconcept/docker-stack-deploy@v1.0.1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         remote_host: ${{ secrets.HOST }}
  #         remote_user: ${{ secrets.USERNAME }}
  #         remote_private_key: ${{ secrets.PRIVATE_KEY }}
  #         stack_file: docker-compose.yml
  #         stack_name: demo
  #         env_file: .env
