name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: katleta/test-web-app:latest

  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/app &&
            docker login -p ${{secrets.DOCKER_PASSWORD}} -u ${{secrets.DOCKER_USERNAME}} &&
            docker pull katleta/test-web-app &&
            docker stop app &&
            docker rm app &&
            docker run -d --name=app --restart on-failure 3 katleta/test-web-app:latest &&
            docker prune -af;
